---
# tasks file for general-config

- name: include windows specific tasks
  include_tasks: Windows.yml
  when: ansible_os_family == "Windows"

- name: include redhat specific tasks
  include_tasks: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: setup ntp
  include_role:
    name: ntp
