- name: create normal SSH key
  user:
    name: "{{ ansible_user_id }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa

- name: create root SSH key
  become: yes
  user:
    name: "root"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa

- name: install git-lfs prereqs
  become: yes
  yum:
    name:
      - pygpgme
      - yum-utils
    state: latest

- name: add the github git-lfs repo
  become: yes
  yum_repository:
    name: github_git-lfs
    description: ""
    baseurl: "{{ general_config_git_lfs_yum_repo_base_url }}"
    repo_gpgcheck: yes
    gpgcheck: no
    enabled: yes
    gpgkey: "{{ general_config_git_lfs_yum_repo_gpg_key }}"
    sslverify: yes
    sslcacert: "{{ general_config_git_lfs_yum_repo_sslcacert }}"
    metadata_expire: "300"

- name: install git-lfs
  become: yes
  yum:
    name: git-lfs
    state: latest

- name: enable git-lfs
  become: yes
  shell: git lfs install

- name: upgrade all yum packages
  become: yes
  yum:
    name: '*'
    state: latest

- name: place the pip config file
  become: yes
  template:
    src: templates/pip.j2
    dest: /etc/pip.conf
    owner: root
    group: wheel
    mode: "0644"

- name: install pip packages
  become: yes
  pip:
    name: "{{ item }}"
    state: latest
  loop:
    - pip
    - setuptools
    - virtualenv

- name: install 7zip
  become: yes
  yum:
    name: 'p7zip'
    state: latest