- name: create normal SSH key
  user:
    name: "{{ ansible_user_id }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa

- name: create root SSH key
  become: yes
  user:
    name: "root"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa

- name: install git-lfs prereqs
  become: yes
  yum:
    name:
      - pygpgme
      - yum-utils
    state: latest

# https://github.com/git-lfs/git-lfs/wiki/Installation#rhelcentos
- name: add the github git-lfs repo
  become: yes
  yum_repository:
    name: github_git-lfs
    description: ""
    baseurl: "{{ general_config_git_lfs_yum_repo_base_url }}"
    repo_gpgcheck: yes
    gpgcheck: no
    enabled: yes
    gpgkey: "{{ general_config_git_lfs_yum_repo_gpg_key }}"
    sslverify: yes
    sslcacert: "{{ general_config_git_lfs_yum_repo_sslcacert }}"
    metadata_expire: "300"

- name: install git-lfs
  become: yes
  yum:
    name: git-lfs
    state: latest

- name: enable git-lfs
  become: yes
  shell: git lfs install

- name: modify git config http ca info
  become: yes
  shell: git config --global http."{{ general_config_git_https_server }}".sslCAInfo "{{ general_config_git_sslcainfo }}"
  when: general_config_git_sslcainfo is defined and general_config_git_https_server is defined

- name: upgrade all yum packages
  become: yes
  yum:
    name: '*'
    state: latest

- name: place the pip config file
  become: yes
  template:
    src: templates/pip.j2
    dest: /etc/pip.conf
    owner: root
    group: wheel
    mode: "0644"

- name: remove pip package with yum
  become: yes
  yum:
    name: python2-pip
    state: absent

- name: download pip helper script
  become: yes
  get_url:
    url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
    dest: /tmp/get-pip.py
    mode: '0555'

- name: install pip from helper script
  become: yes
  shell: python /tmp/get-pip.py

- name: install pip packages
  become: yes
  pip:
    name:
      - setuptools
      - virtualenv
    state: latest

- name: install 7zip
  become: yes
  yum:
    name: 'p7zip'
    state: latest