---

- name: check for user SSH key
  ansible.builtin.stat:
    path: /home/{{ ansible_user_id }}/.ssh/id_rsa
  register: general_config_user_ssh_key_stat

- name: create normal SSH key
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
  when: not general_config_user_ssh_key_stat.stat.exists

- name: check for root SSH key
  become: yes
  ansible.builtin.stat:
    path: /root/.ssh/id_rsa
  register: general_config_root_ssh_key_stat

- name: create root SSH key
  become: yes
  ansible.builtin.user:
    name: "root"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
  when: not general_config_root_ssh_key_stat.stat.exists

- name: download public ca certificates
  become: yes
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "/etc/pki/ca-trust/source/anchors/"
    mode: 0644
  loop: "{{ general_config_ca_certs_download }}"
  when: general_config_ca_certs_download is defined

- name: copy public ca certificates
  become: yes
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/pki/ca-trust/source/anchors/"
    mode: 0644
  loop: "{{ general_config_ca_certs_copy }}"
  when: general_config_ca_certs_copy is defined

- name: import the public ca certificates
  become: yes
  ansible.builtin.shell: update-ca-trust
  when: general_config_ca_certs_download is defined or general_config_ca_certs_copy is defined

# https://github.com/git-lfs/git-lfs/wiki/Installation#rhelcentos
- name: add the github git-lfs repo
  become: yes
  ansible.builtin.yum_repository:
    name: github_git-lfs
    description: ""
    baseurl: "{{ general_config_git_lfs_yum_repo_base_url }}"
    repo_gpgcheck: yes
    gpgcheck: no
    enabled: yes
    gpgkey: "{{ general_config_git_lfs_yum_repo_gpg_key }}"
    sslverify: yes
    sslcacert: "{{ general_config_git_lfs_yum_repo_sslcacert }}"
    metadata_expire: "300"

- name: install python2-dnf
  become: yes
  ansible.builtin.yum:
    name: python2-dnf
    state: latest
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version <= '7'

- name: clean the system package cache
  become: yes
  ansible.builtin.shell: dnf clean all

- name: upgrade all packages
  become: yes
  ansible.builtin.dnf:
    name: '*'
    state: latest

- name: install git-lfs prereqs
  become: yes
  ansible.builtin.dnf:
    name:
      - pygpgme
      - yum-utils
    state: latest
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version <= '7'

- name: install git-lfs
  become: yes
  ansible.builtin.dnf:
    name: git-lfs
    state: latest

- name: enable git-lfs
  ansible.builtin.shell: git lfs install

- name: enable git-lfs (become)
  become: yes
  ansible.builtin.shell: git lfs install

- name: modify git config http ca info
  become: yes
  ansible.builtin.shell: git config --system http."{{ general_config_git_https_server }}".sslCAInfo "{{ general_config_git_sslcainfo }}"
  when: general_config_git_sslcainfo is defined and general_config_git_https_server is defined

- name: place the pip config file
  become: yes
  ansible.builtin.template:
    src: templates/pip.j2
    dest: /etc/pip.conf
    owner: root
    group: root
    mode: "0444"

# CentOS 8 and Stream baselines are assumed to already have latest available python and pip installed from the OS package manager.
- name: remove pip package with yum
  become: yes
  ansible.builtin.dnf:
    name: python2-pip
    state: absent
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version <= '7'

- name: download pip helper script
  become: yes
  ansible.builtin.get_url:
    url: "{{ general_config_pip_download_host }}/pip/2.7/get-pip.py"
    dest: /tmp/get-pip.py
    mode: '0555'
    force: yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version <= '7'

- name: adjust the path
  become: yes
  ansible.builtin.copy:
    src: "files/path_user_local_bin.sh"
    dest: /etc/profile.d/path_user_local_bin.sh
    mode: '0755'
    force: yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version <= '7'

- name: install pip from helper script (become)
  become: yes
  ansible.builtin.shell: python /tmp/get-pip.py
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version <= '7'

- name: install pip from helper script
  ansible.builtin.shell: python /tmp/get-pip.py
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version <= '7'

- name: install pip packages
  ansible.builtin.pip:
    name:
      - setuptools
      - virtualenv
    umask: "0022"
    state: latest

- name: install 7zip
  become: yes
  ansible.builtin.dnf:
    name: 'p7zip'
    state: latest