- name: create normal SSH key
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa

- name: create root SSH key
  become: yes
  ansible.builtin.user:
    name: "root"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa

# https://github.com/git-lfs/git-lfs/wiki/Installation#rhelcentos
- name: add the github git-lfs repo
  become: yes
  ansible.builtin.yum_repository:
    name: github_git-lfs
    description: ""
    baseurl: "{{ general_config_git_lfs_yum_repo_base_url }}"
    repo_gpgcheck: yes
    gpgcheck: no
    enabled: yes
    gpgkey: "{{ general_config_git_lfs_yum_repo_gpg_key }}"
    sslverify: yes
    sslcacert: "{{ general_config_git_lfs_yum_repo_sslcacert }}"
    metadata_expire: "300"

- name: upgrade all packages
  become: yes
  ansible.builtin.dnf:
    name: '*'
    state: latest

- name: install git-lfs
  become: yes
  ansible.builtin.dnf:
    name: git-lfs
    state: latest

- name: enable git-lfs
  become: yes
  ansible.builtin.shell: git lfs install

- name: modify git config http ca info
  become: yes
  ansible.builtin.shell: git config --global http."{{ general_config_git_https_server }}".sslCAInfo "{{ general_config_git_sslcainfo }}"
  when: general_config_git_sslcainfo is defined and general_config_git_https_server is defined

- name: place the pip config file
  become: yes
  ansible.builtin.template:
    src: templates/pip.j2
    dest: /etc/pip.conf
    owner: root
    group: wheel
    mode: "0644"

- name: install pip packages
  become: yes
  ansible.builtin.pip:
    name:
      - setuptools
      - virtualenv
    state: latest

- name: install 7zip
  become: yes
  ansible.builtin.dnf:
    name: 'p7zip'
    state: latest