---

- name: check if a reboot is needed
  ansible.windows.win_shell: (Get-WURebootStatus)."RebootRequired"
  register: general_config_win_update_pre_reboot_required

- name: reboot if needed
  ansible.windows.win_reboot:
  when: general_config_win_update_pre_reboot_required.stdout == "False"

- name: install windows update
  become: yes
  ansible.windows.win_powershell:
    script: |
      $ProgressPreference = "SilentlyContinue"
      Get-WindowsUpdate -Install -AcceptAll -IgnoreReboot -Verbose
  # Allow updates to run for 2 hours.
  async: 7200
  poll: 5
  register: general_config_win_updates_install

- name: show win updates installed
  ansible.builtin.debug:
    var: general_config_win_updates_install.verbose

- name: check again if a reboot is needed
  ansible.windows.win_shell: (Get-WURebootStatus)."RebootRequired"
  register: general_config_win_update_post_reboot_required

- name: run windows updates again if a post reboot is required, there might be more updates
  ansible.builtin.include_tasks: Windows_updates.yml
  when: general_config_win_update_post_reboot_required.stdout == "True"

