---

- name: check if a reboot is needed
  ansible.windows.win_shell: (Get-WURebootStatus)."RebootRequired"
  register: general_config_win_update_pre_reboot_required

- name: reboot if needed
  ansible.windows.win_reboot:
  when: general_config_win_update_pre_reboot_required.stdout == "False"

- name: get available updates
  ansible.windows.win_shell: Get-WindowsUpdate -Verbose *>log.txt; cat log.txt; rm log.txt
  register: general_config_win_updates_list

- name: list available updates
  ansible.builtin.debug:
    var: general_config_win_updates_list.stdout_lines

- name: run windows update (2 hr max)
  ansible.windows.win_shell: $ProgressPreference = "SilentlyContinue"; Install-WindowsUpdate -AcceptAll -IgnoreReboot -Verbose *>log.txt; cat log.txt; rm log.txt
  # https://thinkpowershell.com/hide-powershell-progress-bars/
  # Allow updates to run for 2 hours.
  async: 7200
  poll: 5
  register: general_config_win_updates_install

- name: show win updates install
  ansible.builtin.debug:
    var: general_config_win_updates_install.stdout_lines

- name: check again if a reboot is needed
  ansible.windows.win_shell: (Get-WURebootStatus)."RebootRequired"
  register: general_config_win_update_post_reboot_required

- name: run windows updates again if a post reboot is required, there might be more updates
  ansible.builtin.include_tasks: Windows_updates.yml
  when: general_config_win_update_post_reboot_required.stdout == "True"

