---

- name: fetch the private ssh key
  ansible.builtin.fetch:
    src: "C:\\Users\\{{ ansible_user }}\\.ssh\\id_rsa"
    dest: "{{ role_path }}/files/id_rsa"
    flat: yes

# The assumption here is that if there is a private key but not public, it will generate the public key from the private key instead of generating both anew.
- name: generate the public key for the fetched private key
  local_action:
    module: ansible.builtin.user
    # It is safe to assume that there is a service user on the ansible controller.
    name: service
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: "{{ role_path }}/files/id_rsa"

- name: copy the public ssh key
  ansible.windows.win_copy:
    src: "{{ role_path }}/files/id_rsa.pub"
    dest: "%USERPROFILE%\\.ssh\\id_rsa.pub"